language: node_js
node_js:
  - "node"
script:
  - npm run test_ci
before_script:
  - echo 'Europe/Stockholm' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
branches:
  only:
  - test-ical-fix
